
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AdminClients = lazy(() => import("./pages/AdminClients.tsx"));
const AdminClientsProjets = lazy(() => import("./pages/AdminClientsProjets.tsx"));
const AdminGestionClients = lazy(() => import("./pages/AdminGestionClients.tsx"));
const AdminGestionProjets = lazy(() => import("./pages/AdminGestionProjets.tsx"));
const AdminInvoicing = lazy(() => import("./pages/AdminInvoicing.tsx"));
const AdminProjects = lazy(() => import("./pages/AdminProjects.tsx"));
const AdminValidationPrestations = lazy(() => import("./pages/AdminValidationPrestations.tsx"));
const AdminValidationUtilisateurs = lazy(() => import("./pages/AdminValidationUtilisateurs.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Connexion = lazy(() => import("./pages/Connexion.tsx"));
const CreerPrestation = lazy(() => import("./pages/CreerPrestation.tsx"));
const DashboardAdminPrestations = lazy(() => import("./pages/DashboardAdminPrestations.tsx"));
const DashboardCollaborateur = lazy(() => import("./pages/DashboardCollaborateur.tsx"));
const EnAttenteValidation = lazy(() => import("./pages/EnAttenteValidation.tsx"));
const EncoderPrestation = lazy(() => import("./pages/EncoderPrestation.tsx"));
const GestionClientsProjets = lazy(() => import("./pages/GestionClientsProjets.tsx"));
const Inscription = lazy(() => import("./pages/Inscription.tsx"));
const MettreAJourMotDePasse = lazy(() => import("./pages/MettreAJourMotDePasse.tsx"));
const MotDePasseOublie = lazy(() => import("./pages/MotDePasseOublie.tsx"));
const ProjectManagement = lazy(() => import("./pages/ProjectManagement.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-clients", element: <AdminClients />},
	{ path: "/adminclients", element: <AdminClients />},
	{ path: "/admin-clients-projets", element: <AdminClientsProjets />},
	{ path: "/adminclientsprojets", element: <AdminClientsProjets />},
	{ path: "/admin-gestion-clients", element: <AdminGestionClients />},
	{ path: "/admingestionclients", element: <AdminGestionClients />},
	{ path: "/admin-gestion-projets", element: <AdminGestionProjets />},
	{ path: "/admingestionprojets", element: <AdminGestionProjets />},
	{ path: "/admin-invoicing", element: <AdminInvoicing />},
	{ path: "/admininvoicing", element: <AdminInvoicing />},
	{ path: "/admin-projects", element: <AdminProjects />},
	{ path: "/adminprojects", element: <AdminProjects />},
	{ path: "/admin-validation-prestations", element: <AdminValidationPrestations />},
	{ path: "/adminvalidationprestations", element: <AdminValidationPrestations />},
	{ path: "/admin-validation-utilisateurs", element: <AdminValidationUtilisateurs />},
	{ path: "/adminvalidationutilisateurs", element: <AdminValidationUtilisateurs />},
	{ path: "/", element: <App />},
	{ path: "/connexion", element: <Connexion />},
	{ path: "/creer-prestation", element: <CreerPrestation />},
	{ path: "/creerprestation", element: <CreerPrestation />},
	{ path: "/dashboard-admin-prestations", element: <DashboardAdminPrestations />},
	{ path: "/dashboardadminprestations", element: <DashboardAdminPrestations />},
	{ path: "/dashboard-collaborateur", element: <DashboardCollaborateur />},
	{ path: "/dashboardcollaborateur", element: <DashboardCollaborateur />},
	{ path: "/en-attente-validation", element: <EnAttenteValidation />},
	{ path: "/enattentevalidation", element: <EnAttenteValidation />},
	{ path: "/encoder-prestation", element: <EncoderPrestation />},
	{ path: "/encoderprestation", element: <EncoderPrestation />},
	{ path: "/gestion-clients-projets", element: <GestionClientsProjets />},
	{ path: "/gestionclientsprojets", element: <GestionClientsProjets />},
	{ path: "/inscription", element: <Inscription />},
	{ path: "/mettre-a-jour-mot-de-passe", element: <MettreAJourMotDePasse />},
	{ path: "/mettreajourmotdepasse", element: <MettreAJourMotDePasse />},
	{ path: "/mot-de-passe-oublie", element: <MotDePasseOublie />},
	{ path: "/motdepasseoublie", element: <MotDePasseOublie />},
	{ path: "/project-management", element: <ProjectManagement />},
	{ path: "/projectmanagement", element: <ProjectManagement />},
	{ path: "/reset-password", element: <ResetPassword />},
	{ path: "/resetpassword", element: <ResetPassword />},

];
