// This file contains custom TypeScript types used across the frontend application.

// Based on Supabase table 'clients'
export interface Client {
  id: string; // UUID generated by Supabase
  created_at?: string; // Supabase default timestamp
  nom: string;
  adresse?: string | null;
  email_facturation?: string | null;
  telephone?: string | null; // Note: Removed accent from 'téléphone' for likely DB compatibility
  tarif_horaire?: number | null;
}

// Based on Supabase table 'projects'
export interface Project {
  id: string; // UUID generated by Supabase
  created_at?: string; // Supabase default timestamp
  nom: string;
  client_id: string; // Foreign key to Client.id (UUID)
}

// Re-exporting UserInfo from brain types for easier access if needed elsewhere?
// Alternatively, import directly from 'brain' or define a specific AppUser type here.
// Example re-export:
// export type { UserInfo } from '../brain/data-contracts';


// Add other shared frontend types below.
